theme: jekyll-theme-cayman
plugins:
  - jemoji
title: Welcome to Kelly Lin's interview questions blog!
#sidebar-about-description: "简单的描述一下你自己"
#sidebar-avatar: img/bfs.png
sidebar:
  nav: "img/bfs.png"
